In [1]:

import pandas as pd
import numpy as np
import csv

In [2]:
!pip install -q -U kagglehub

In [3]:
import kagglehub

dataset_folder = kagglehub.dataset_download(
    "sumitm004/arxiv-scientific-research-papers-dataset",
    output_dir="/content/arxiv_data",
    force_download=True
)

print("Dataset downloaded successfully!")

Downloading to /content/arxiv_data/3.archive...

100%|██████████| 144M/144M [00:00<00:00, 166MB/s]

Extracting files...

Dataset downloaded successfully!

In [4]:
import kagglehub

kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [5]:
import glob
import os

csv_files = glob.glob(
    "/content/arxiv_data/**/*.csv",
    recursive=True
)

matching_files = [
    file for file in csv_files
    if os.path.basename(file).lower()
    == "arxiv_scientific_dataset.csv"
]

if len(matching_files) == 0:
    raise FileNotFoundError(
        "The arXiv scientific dataset CSV was not found."
    )

csv_file = matching_files[0]

print("CSV file found successfully!")
print(os.path.basename(csv_file))

CSV file found successfully!
arXiv_scientific_dataset.csv

In [6]:
import pandas as pd

df = pd.read_csv(
    csv_file,
    low_memory=False
)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (287421, 10)

,id,title,category,category_code,published_date,updated_date,authors,first_author,summary,summary_word_count
0,cs-9308101v1,Dynamic Backtracking,Artificial Intelligence,cs.AI,8/1/93,8/1/93,['M. L. Ginsberg'],'M. L. Ginsberg',Because of their occasional need to return to ...,79
1,cs-9308102v1,A Market-Oriented Programming Environment and ...,Artificial Intelligence,cs.AI,8/1/93,8/1/93,['M. P. Wellman'],'M. P. Wellman',Market price systems constitute a well-underst...,119
2,cs-9309101v1,An Empirical Analysis of Search in GSAT,Artificial Intelligence,cs.AI,9/1/93,9/1/93,"['I. P. Gent', 'T. Walsh']",'I. P. Gent',We describe an extensive study of search in GS...,167
3,cs-9311101v1,The Difficulties of Learning Logic Programs wi...,Artificial Intelligence,cs.AI,11/1/93,11/1/93,"['F. Bergadano', 'D. Gunetti', 'U. Trinchero']",'F. Bergadano',As real logic programmers normally use cut (!)...,174
4,cs-9311102v1,Software Agents: Completing Patterns and Const...,Artificial Intelligence,cs.AI,11/1/93,11/1/93,"['J. C. Schlimmer', 'L. A. Hermens']",'J. C. Schlimmer',To support the goal of allowing users to recor...,187

In [7]:
# Dataset information
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287421 entries, 0 to 287420
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  287421 non-null  object
 1   title               287421 non-null  object
 2   category            287421 non-null  object
 3   category_code       287421 non-null  object
 4   published_date      287421 non-null  object
 5   updated_date        287421 non-null  object
 6   authors             287421 non-null  object
 7   first_author        287421 non-null  object
 8   summary             287421 non-null  object
 9   summary_word_count  287421 non-null  int64
dtypes: int64(1), object(9)
memory usage: 21.9+ MB

In [8]:
# Unique values
print("\nUnique values per column:")
print(df.nunique())

Unique values per column:
id                    287421
title                 287306
category                 146
category_code            147
published_date          7769
updated_date            7706
authors               267660
first_author          155623
summary               287357
summary_word_count       349
dtype: int64

In [9]:
# Check and remove complete duplicate rows

rows_before = len(df)
duplicate_rows = df.duplicated().sum()

print("Rows before duplicate removal:", rows_before)
print("Complete duplicate rows found:", duplicate_rows)

df = df.drop_duplicates().reset_index(drop=True)

rows_after = len(df)
rows_removed = rows_before - rows_after

print("Rows removed:", rows_removed)
print("Rows after duplicate removal:", rows_after)
print("Final shape after duplicate removal:", df.shape)

# Confirm that the calculated values are consistent
assert rows_removed == duplicate_rows, (
    "The number removed does not match the duplicate count."
)

Rows before duplicate removal: 287421
Complete duplicate rows found: 0
Rows removed: 0
Rows after duplicate removal: 287421
Final shape after duplicate removal: (287421, 10)

In [10]:
df.head(5)

,id,title,category,category_code,published_date,updated_date,authors,first_author,summary,summary_word_count
0,cs-9308101v1,Dynamic Backtracking,Artificial Intelligence,cs.AI,8/1/93,8/1/93,['M. L. Ginsberg'],'M. L. Ginsberg',Because of their occasional need to return to ...,79
1,cs-9308102v1,A Market-Oriented Programming Environment and ...,Artificial Intelligence,cs.AI,8/1/93,8/1/93,['M. P. Wellman'],'M. P. Wellman',Market price systems constitute a well-underst...,119
2,cs-9309101v1,An Empirical Analysis of Search in GSAT,Artificial Intelligence,cs.AI,9/1/93,9/1/93,"['I. P. Gent', 'T. Walsh']",'I. P. Gent',We describe an extensive study of search in GS...,167
3,cs-9311101v1,The Difficulties of Learning Logic Programs wi...,Artificial Intelligence,cs.AI,11/1/93,11/1/93,"['F. Bergadano', 'D. Gunetti', 'U. Trinchero']",'F. Bergadano',As real logic programmers normally use cut (!)...,174
4,cs-9311102v1,Software Agents: Completing Patterns and Const...,Artificial Intelligence,cs.AI,11/1/93,11/1/93,"['J. C. Schlimmer', 'L. A. Hermens']",'J. C. Schlimmer',To support the goal of allowing users to recor...,187

In [11]:
# Count duplicate rows
duplicates = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicates}")

Number of duplicate rows: 0

In [12]:
# Check for missing values in each individual column
print("Missing values per column:")
print(df.isnull().sum())


df.isnull().sum()

Missing values per column:
id                    0
title                 0
category              0
category_code         0
published_date        0
updated_date          0
authors               0
first_author          0
summary               0
summary_word_count    0
dtype: int64

id                    0
title                 0
category              0
category_code         0
published_date        0
updated_date          0
authors               0
first_author          0
summary               0
summary_word_count    0
dtype: int64

In [13]:

# Remove duplicate rows if any
df = df.drop_duplicates()

print("Shape after removing duplicates:")
print(df.shape)

Shape after removing duplicates:
(287421, 10)

In [14]:
# Clean text columns without converting missing values to strings
text_columns = [
    "id",
    "title",
    "category",
    "category_code",
    "authors",
    "first_author",
    "summary"
]

for col in text_columns:
    # Convert blank spaces into real missing values
    df[col] = df[col].replace(r"^\s*$", np.nan, regex=True)

    # Remove spaces while preserving missing values
    df[col] = df[col].str.strip()

print("Text columns cleaned successfully.")
print(df.isnull().sum())

Text columns cleaned successfully.
id                    0
title                 0
category              0
category_code         0
published_date        0
updated_date          0
authors               0
first_author          0
summary               0
summary_word_count    0
dtype: int64

In [15]:
# Convert date columns to datetime
df["published_date"] = pd.to_datetime(
    df["published_date"],
    format="mixed",
    errors="coerce"
)

df["updated_date"] = pd.to_datetime(
    df["updated_date"],
    format="mixed",
    errors="coerce"
)

print(df[["published_date", "updated_date"]].dtypes)

print("\nMissing dates after conversion:")
print(df[["published_date", "updated_date"]].isnull().sum())

published_date    datetime64[ns]
updated_date      datetime64[ns]
dtype: object

Missing dates after conversion:
published_date    0
updated_date      0
dtype: int64

In [16]:
# Remove rows missing essential information
important_columns = [
    "id",
    "title",
    "category",
    "summary"
]

rows_before = len(df)

df = df.dropna(subset=important_columns).copy()

rows_removed = rows_before - len(df)

# Fill optional author information
df["authors"] = df["authors"].fillna("Unknown")
df["first_author"] = df["first_author"].fillna("Unknown")

# Recalculate summary word count
df["summary_word_count"] = (
    df["summary"]
    .str.split()
    .str.len()
)

df = df.reset_index(drop=True)

print("Rows removed:", rows_removed)
print("Final dataset shape:", df.shape)

print("\nRemaining missing values:")
print(df.isnull().sum())

Rows removed: 0
Final dataset shape: (287421, 10)

Remaining missing values:
id                    0
title                 0
category              0
category_code         0
published_date        0
updated_date          0
authors               0
first_author          0
summary               0
summary_word_count    0
dtype: int64

In [17]:
# Save the newest cleaned dataset using a unique name
df.to_csv(
    "cleaned_arxiv_datasets.csv",
    index=False
)

# Reload it immediately to confirm the saved file
check_df = pd.read_csv(
    "cleaned_arxiv_datasets.csv",
    low_memory=False
)

print("Dataset before saving:", df.shape)
print("Saved file after reloading:", check_df.shape)

Dataset before saving: (287421, 10)
Saved file after reloading: (287421, 10)